<a href="https://colab.research.google.com/github/Arif118/Cancer-Patient-Clustering-/blob/main/Crop_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt
#import seaborn as sns

In [ ]:
df = pd.read_csv('/content/Crop_recommendation.xls')
df = pd.DataFrame(df)
df.sample(5)

        N    P    K  temperature   humidity        ph    rainfall     label
1977  105   56   15    25.967797  81.979043  7.272316   74.141690    cotton
1085  102   73   52    27.912210  83.363077  6.356091   90.242115    banana
601     8   54   20    28.334043  80.772760  7.034214   38.797641  mungbean
1805    7   11   32    29.259029  95.112947  5.542169  184.762450   coconut
1582    9  143  197    23.750331  92.881605  5.570021  117.660283     apple

In [ ]:
df.shape

(2200, 8)

In [ ]:
df['label'].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

In [ ]:
labels = df['label'].unique()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

In [ ]:
df.sample(5)

       N    P    K  temperature   humidity        ph    rainfall  label
1139   9   29   34    29.384716  45.887447  5.727423  100.812466     12
1535  23  138  195    22.490951  91.702927  5.795986  124.391510      0
1699  31   26    9    11.698946  93.256389  7.566166  103.200599     16
1219   4  136  204    29.937076  81.777135  5.898944   65.522793      7
175   77   52   17    24.863749  65.742005  5.714800   75.822705     11

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.2, random_state=42)
#x_test

In [ ]:
model = RandomForestClassifier(n_estimators=75, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(n_estimators=75, random_state=42)

In [ ]:
model.score(x_test, y_test)

0.9931818181818182

In [ ]:
model.feature_importances_

array([0.10931225, 0.14289148, 0.18103484, 0.07579999, 0.21147856,
       0.05164419, 0.22783869])

In [ ]:
#prediction = model.predict(x_test)
#prediction

In [ ]:
#prediction_x = model.predict([[92,45,36,38,77,6.2,87]])
#labels[prediction_x][0]

In [ ]:
user_input = input('Enter values (N,P,K,temp,hum,ph,rain): ')
inp_data = [[float(i) for i in user_input.split(',')]]
print(f'Recommended crop: {le.inverse_transform(model.predict(inp_data))[0]}')